runtime: python313

# Google Cloud App Engine configuration
instance_class: F2

# Environment variables
env_variables:
  FLASK_ENV: production
  PYTHONUNBUFFERED: "1"

# Automatic scaling
automatic_scaling:
  min_instances: 0
  max_instances: 10
  target_cpu_utilization: 0.65

handlers:
  - url: /static
    static_dir: static
  - url: /.*
    script: auto
    secure: always
    redirect_http_response_code: 301
